"""add_contact_submissions_table

Revision ID: 4733c7cc85eb
Revises: 600716d766da
Create Date: 2026-03-12 07:08:49.053474

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4733c7cc85eb'
down_revision: Union[str, None] = '600716d766da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
