"""add_kyc_document_fields_to_users

Revision ID: 600716d766da
Revises: e3f1a8b2c9d7
Create Date: 2026-03-10 21:15:24.990408

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '600716d766da'
down_revision: Union[str, None] = 'e3f1a8b2c9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kyc_document_front', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kyc_document_back', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kyc_document_back')
    op.drop_column('users', 'kyc_document_front')
    # ### end Alembic commands ###
