"""add_assignment_columns_and_chat_table

Revision ID: 7a78745b35be
Revises: 9f2d5db0c4f1
Create Date: 2026-03-24 21:39:46.410209

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7a78745b35be'
down_revision: Union[str, None] = '9f2d5db0c4f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('assignment_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'applications', 'users', ['assigned_to_id'], ['id'])
    op.drop_index(op.f('ix_users_ghana_card_hash'), table_name='users', postgresql_where='(ghana_card_hash IS NOT NULL)')
    op.create_index(op.f('ix_users_ghana_card_hash'), 'users', ['ghana_card_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ghana_card_hash'), table_name='users')
    op.create_index(op.f('ix_users_ghana_card_hash'), 'users', ['ghana_card_hash'], unique=True, postgresql_where='(ghana_card_hash IS NOT NULL)')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'assignment_note')
    op.drop_column('applications', 'assigned_at')
    op.drop_column('applications', 'assigned_to_id')
    # ### end Alembic commands ###
