"""initial

Revision ID: b82ca6dd623d
Revises: 
Create Date: 2026-02-26 02:19:37.432957

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b82ca6dd623d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_delivery_addresses_id'), table_name='delivery_addresses')
    op.drop_table('delivery_addresses')
    op.drop_index(op.f('ix_payment_plans_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.add_column('applications', sa.Column('applicant_id', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('reviewed_by_id', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('delivery_method', sa.Enum('PICKUP', 'DELIVERY', name='deliverymethod'), nullable=False))
    op.add_column('applications', sa.Column('child_other_names', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('child_region_of_birth', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('child_district_of_birth', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('child_nationality', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('child_birth_order', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('father_first_name', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('father_last_name', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('father_other_names', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('father_date_of_birth', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('father_address', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('mother_first_name', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('mother_last_name', sa.String(length=100), nullable=False))
    op.add_column('applications', sa.Column('mother_other_names', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('mother_date_of_birth', sa.Date(), nullable=True))
    op.add_column('applications', sa.Column('mother_address', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('hospital_name', sa.String(length=200), nullable=True))
    op.add_column('applications', sa.Column('hospital_address', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('attending_physician', sa.String(length=200), nullable=True))
    op.add_column('applications', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('delivery_region', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('delivery_district', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('delivery_digital_address', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('delivery_fee', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('delivery_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('processing_fee', sa.Float(), nullable=False))
    op.add_column('applications', sa.Column('total_fee', sa.Float(), nullable=False))
    op.add_column('applications', sa.Column('additional_info_request', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('expected_ready_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('collection_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('applications', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PAYMENT_PENDING', 'PAYMENT_COMPLETED', 'PROCESSING', 'READY', 'COLLECTED', 'DELIVERED', 'CANCELLED', name='applicationstatus'),
               nullable=False)
    op.alter_column('applications', 'service_plan',
               existing_type=postgresql.ENUM('NORMAL', 'EXPRESS', name='serviceplan'),
               nullable=False)
    op.alter_column('applications', 'child_date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('applications', 'child_gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('MALE', 'FEMALE', name='gender'),
               existing_nullable=False)
    op.alter_column('applications', 'child_place_of_birth',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('applications', 'mother_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('applications', 'informant_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
    op.alter_column('applications', 'informant_relationship',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'informant_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(op.f('applications_assigned_staff_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['applicant_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'users', ['reviewed_by_id'], ['id'])
    op.drop_column('applications', 'child_birth_region')
    op.drop_column('applications', 'expected_completion_date')
    op.drop_column('applications', 'additional_data')
    op.drop_column('applications', 'completed_date')
    op.drop_column('applications', 'user_id')
    op.drop_column('applications', 'mother_full_name')
    op.drop_column('applications', 'assigned_staff_id')
    op.drop_column('applications', 'reviewed_at')
    op.drop_column('applications', 'child_middle_name')
    op.drop_column('applications', 'child_birth_city')
    op.drop_column('applications', 'father_full_name')
    op.drop_column('applications', 'application_type')
    op.drop_column('applications', 'child_birth_weight')
    op.add_column('audit_logs', sa.Column('http_method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'PASSWORD_RESET', 'STATUS_CHANGED', 'DOCUMENT_UPLOADED', 'DOCUMENT_VERIFIED', 'DOCUMENT_REJECTED', 'PAYMENT_INITIATED', 'PAYMENT_CONFIRMED', 'CERTIFICATE_GENERATED', 'CERTIFICATE_PRINTED', 'APPLICATION_SUBMITTED', 'APPLICATION_APPROVED', 'APPLICATION_REJECTED', 'PENALTY_APPLIED', 'PENALTY_WAIVED', 'DELIVERY_ASSIGNED', 'EXPORT_DATA', 'BULK_ACTION', name='auditaction'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('audit_logs_application_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_certificate_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_payment_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'additional_data')
    op.drop_column('audit_logs', 'application_id')
    op.drop_column('audit_logs', 'payment_id')
    op.drop_column('audit_logs', 'changes')
    op.drop_column('audit_logs', 'certificate_id')
    op.drop_column('audit_logs', 'resource_identifier')
    op.drop_column('audit_logs', 'method')
    op.drop_column('audit_logs', 'user_role')
    op.drop_column('audit_logs', 'user_email')
    op.add_column('certificates', sa.Column('generated_by_id', sa.Integer(), nullable=True))
    op.add_column('certificates', sa.Column('printed_by_id', sa.Integer(), nullable=True))
    op.add_column('certificates', sa.Column('revoked_by_id', sa.Integer(), nullable=True))
    op.add_column('certificates', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('certificates', sa.Column('qr_code_data', sa.Text(), nullable=True))
    op.add_column('certificates', sa.Column('qr_code_path', sa.String(length=500), nullable=True))
    op.add_column('certificates', sa.Column('blockchain_hash', sa.String(length=255), nullable=True))
    op.add_column('certificates', sa.Column('revocation_reason', sa.Text(), nullable=True))
    op.add_column('certificates', sa.Column('replacement_certificate_id', sa.Integer(), nullable=True))
    op.add_column('certificates', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('certificates', sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('certificates', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('certificates', 'status',
               existing_type=postgresql.ENUM('PENDING', 'GENERATED', 'PRINTED', 'READY', 'COLLECTED', 'DELIVERED', 'UNCOLLECTED', 'PENALTY_APPLIED', 'CANCELLED', name='certificatestatus'),
               nullable=False)
    op.drop_constraint(op.f('certificates_printed_by_fkey'), 'certificates', type_='foreignkey')
    op.drop_constraint(op.f('certificates_user_id_fkey'), 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'users', ['revoked_by_id'], ['id'])
    op.create_foreign_key(None, 'certificates', 'users', ['printed_by_id'], ['id'])
    op.create_foreign_key(None, 'certificates', 'certificates', ['replacement_certificate_id'], ['id'])
    op.create_foreign_key(None, 'certificates', 'users', ['generated_by_id'], ['id'])
    op.drop_column('certificates', 'is_collected')
    op.drop_column('certificates', 'penalty_start_date')
    op.drop_column('certificates', 'collector_id_type')
    op.drop_column('certificates', 'delivered_at')
    op.drop_column('certificates', 'print_attempts')
    op.drop_column('certificates', 'penalty_days')
    op.drop_column('certificates', 'penalty_applied')
    op.drop_column('certificates', 'user_confirmed_readiness')
    op.drop_column('certificates', 'collector_id_number')
    op.drop_column('certificates', 'penalty_amount')
    op.drop_column('certificates', 'printed_by')
    op.drop_column('certificates', 'collection_deadline')
    op.drop_column('certificates', 'collected_by')
    op.drop_column('certificates', 'confirmation_date')
    op.drop_column('certificates', 'date_of_issue')
    op.drop_column('certificates', 'last_print_date')
    op.drop_column('certificates', 'collector_relationship')
    op.drop_column('certificates', 'pdf_path')
    op.drop_column('certificates', 'additional_data')
    op.drop_column('certificates', 'user_id')
    op.drop_column('certificates', 'date_ready')
    op.drop_column('certificates', 'qr_code')
    op.drop_column('certificates', 'collected_at')
    op.add_column('deliveries', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('delivery_address', sa.Text(), nullable=False))
    op.add_column('deliveries', sa.Column('delivery_region', sa.String(length=100), nullable=False))
    op.add_column('deliveries', sa.Column('delivery_district', sa.String(length=100), nullable=False))
    op.add_column('deliveries', sa.Column('digital_address', sa.String(length=50), nullable=True))
    op.add_column('deliveries', sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deliveries', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('deliveries', sa.Column('proof_of_delivery', sa.String(length=500), nullable=True))
    op.add_column('deliveries', sa.Column('recipient_signature', sa.Text(), nullable=True))
    op.add_column('deliveries', sa.Column('attempts_count', sa.Integer(), nullable=True))
    op.add_column('deliveries', sa.Column('max_attempts', sa.Integer(), nullable=True))
    op.alter_column('deliveries', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED', name='deliverystatus'),
               nullable=False)
    op.alter_column('deliveries', 'recipient_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('deliveries', 'delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_deliveries_tracking_number'), table_name='deliveries')
    op.create_unique_constraint(None, 'deliveries', ['application_id'])
    op.create_unique_constraint(None, 'deliveries', ['tracking_number'])
    op.drop_constraint(op.f('deliveries_address_id_fkey'), 'deliveries', type_='foreignkey')
    op.drop_constraint(op.f('deliveries_user_id_fkey'), 'deliveries', type_='foreignkey')
    op.drop_constraint(op.f('deliveries_certificate_id_fkey'), 'deliveries', type_='foreignkey')
    op.create_foreign_key(None, 'deliveries', 'users', ['agent_id'], ['id'])
    op.drop_column('deliveries', 'additional_data')
    op.drop_column('deliveries', 'address_id')
    op.drop_column('deliveries', 'user_id')
    op.drop_column('deliveries', 'actual_delivery_date')
    op.drop_column('deliveries', 'certificate_id')
    op.drop_column('deliveries', 'last_updated')
    op.drop_column('deliveries', 'estimated_delivery_date')
    op.drop_column('deliveries', 'notes')
    op.drop_column('deliveries', 'photo_url')
    op.drop_column('deliveries', 'pickup_date')
    op.drop_column('deliveries', 'signature_url')
    op.drop_column('deliveries', 'delivery_attempts')
    op.drop_column('deliveries', 'requested_date')
    op.drop_column('deliveries', 'recipient_email')
    op.drop_column('deliveries', 'current_location')
    op.add_column('notifications', sa.Column('application_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('notification_type', sa.Enum('APPLICATION_SUBMITTED', 'APPLICATION_UNDER_REVIEW', 'APPLICATION_APPROVED', 'APPLICATION_REJECTED', 'ADDITIONAL_INFO_REQUIRED', 'PAYMENT_REQUIRED', 'PAYMENT_RECEIVED', 'CERTIFICATE_READY', 'REMINDER_7_DAYS', 'REMINDER_2_DAYS', 'PENALTY_APPLIED', 'DELIVERY_SCHEDULED', 'DELIVERY_IN_TRANSIT', 'DELIVERY_COMPLETED', 'DELIVERY_FAILED', 'SYSTEM_ANNOUNCEMENT', 'PASSWORD_RESET', 'ACCOUNT_VERIFIED', name='notificationtype'), nullable=False))
    op.add_column('notifications', sa.Column('channel', sa.Enum('EMAIL', 'SMS', 'IN_APP', 'PUSH', name='notificationchannel'), nullable=False))
    op.add_column('notifications', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('notifications', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('notifications', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='notificationstatus'),
               nullable=False)
    op.drop_constraint(op.f('notifications_template_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'applications', ['application_id'], ['id'])
    op.drop_column('notifications', 'content')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'additional_data')
    op.drop_column('notifications', 'context')
    op.drop_column('notifications', 'recipient')
    op.drop_column('notifications', 'template_id')
    op.drop_column('notifications', 'delivered_at')
    op.drop_column('notifications', 'failed_at')
    op.drop_column('notifications', 'subject')
    op.drop_column('notifications', 'priority')
    op.add_column('payments', sa.Column('payment_type', sa.Enum('APPLICATION_FEE', 'DELIVERY_FEE', 'PENALTY_FEE', 'REPLACEMENT_FEE', name='paymenttype'), nullable=False))
    op.add_column('payments', sa.Column('channel', sa.Enum('CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', name='paymentchannel'), nullable=True))
    op.add_column('payments', sa.Column('mobile_money_provider', sa.Enum('MTN', 'VODAFONE', 'AIRTELTIGO', name='mobilemoneyprovider'), nullable=True))
    op.add_column('payments', sa.Column('reference', sa.String(length=100), nullable=False))
    op.add_column('payments', sa.Column('paystack_reference', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('mobile_number', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('refund_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('payments', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'),
               nullable=False)
    op.alter_column('payments', 'receipt_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('payments', 'gateway_response',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_unique_constraint(None, 'payments', ['reference'])
    op.drop_column('payments', 'authorization_url')
    op.drop_column('payments', 'additional_data')
    op.drop_column('payments', 'method')
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'payment_reference')
    op.drop_column('payments', 'receipt_url')
    op.drop_column('payments', 'access_code')
    op.drop_column('payments', 'payer_email')
    op.drop_column('payments', 'payer_name')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'payer_phone')
    op.drop_column('payments', 'purpose')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('other_names', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_verification_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('notification_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_sms', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_push', sa.Boolean(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CITIZEN', 'STAFF', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               nullable=False)
    op.drop_index(op.f('ix_users_ghana_card_number'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['ghana_card_number'])
    op.drop_column('users', 'email_notifications')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'city')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'nationality')
    op.drop_column('users', 'sms_notifications')
    op.drop_column('users', 'verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sms_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_ghana_card_number'), 'users', ['ghana_card_number'], unique=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CITIZEN', 'STAFF', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               nullable=True)
    op.drop_column('users', 'notification_push')
    op.drop_column('users', 'notification_sms')
    op.drop_column('users', 'notification_email')
    op.drop_column('users', 'district')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'phone_verification_code')
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'status')
    op.drop_column('users', 'other_names')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('payments', sa.Column('purpose', postgresql.ENUM('APPLICATION_FEE', 'CERTIFICATE_FEE', 'PENALTY', 'DELIVERY_FEE', name='paymentpurpose'), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('payer_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payer_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('access_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('receipt_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('method', postgresql.ENUM('CASH', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'PAYSTACK', 'STRIPE', name='paymentmethod'), autoincrement=False, nullable=False))
    op.add_column('payments', sa.Column('additional_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('authorization_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='unique')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payments_payment_reference'), 'payments', ['payment_reference'], unique=True)
    op.alter_column('payments', 'gateway_response',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payments', 'receipt_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'),
               nullable=True)
    op.alter_column('payments', 'application_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'expires_at')
    op.drop_column('payments', 'refunded_at')
    op.drop_column('payments', 'refund_reason')
    op.drop_column('payments', 'refund_amount')
    op.drop_column('payments', 'mobile_number')
    op.drop_column('payments', 'paystack_reference')
    op.drop_column('payments', 'reference')
    op.drop_column('payments', 'mobile_money_provider')
    op.drop_column('payments', 'channel')
    op.drop_column('payments', 'payment_type')
    op.add_column('notifications', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('recipient', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('additional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', postgresql.ENUM('EMAIL', 'SMS', 'IN_APP', 'PUSH', name='notificationtype'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_template_id_fkey'), 'notifications', 'notification_templates', ['template_id'], ['id'])
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='notificationstatus'),
               nullable=True)
    op.drop_column('notifications', 'scheduled_at')
    op.drop_column('notifications', 'data')
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'application_id')
    op.add_column('deliveries', sa.Column('current_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('requested_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('delivery_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('signature_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('pickup_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('estimated_delivery_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('certificate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('actual_delivery_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('deliveries', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('additional_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.create_foreign_key(op.f('deliveries_certificate_id_fkey'), 'deliveries', 'certificates', ['certificate_id'], ['id'])
    op.create_foreign_key(op.f('deliveries_user_id_fkey'), 'deliveries', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('deliveries_address_id_fkey'), 'deliveries', 'delivery_addresses', ['address_id'], ['id'])
    op.drop_constraint(None, 'deliveries', type_='unique')
    op.drop_constraint(None, 'deliveries', type_='unique')
    op.create_index(op.f('ix_deliveries_tracking_number'), 'deliveries', ['tracking_number'], unique=True)
    op.alter_column('deliveries', 'delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('deliveries', 'recipient_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('deliveries', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED', name='deliverystatus'),
               nullable=True)
    op.drop_column('deliveries', 'max_attempts')
    op.drop_column('deliveries', 'attempts_count')
    op.drop_column('deliveries', 'recipient_signature')
    op.drop_column('deliveries', 'proof_of_delivery')
    op.drop_column('deliveries', 'failure_reason')
    op.drop_column('deliveries', 'delivered_at')
    op.drop_column('deliveries', 'attempted_at')
    op.drop_column('deliveries', 'scheduled_date')
    op.drop_column('deliveries', 'digital_address')
    op.drop_column('deliveries', 'delivery_district')
    op.drop_column('deliveries', 'delivery_region')
    op.drop_column('deliveries', 'delivery_address')
    op.drop_column('deliveries', 'agent_id')
    op.add_column('certificates', sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('qr_code', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('date_ready', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('certificates', sa.Column('additional_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('pdf_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('collector_relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('last_print_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('date_of_issue', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('confirmation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('collected_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('collection_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('printed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('penalty_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('collector_id_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('user_confirmed_readiness', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('penalty_applied', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('penalty_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('print_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('collector_id_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('penalty_start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('certificates', sa.Column('is_collected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key(op.f('certificates_user_id_fkey'), 'certificates', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('certificates_printed_by_fkey'), 'certificates', 'users', ['printed_by'], ['id'])
    op.alter_column('certificates', 'status',
               existing_type=postgresql.ENUM('PENDING', 'GENERATED', 'PRINTED', 'READY', 'COLLECTED', 'DELIVERED', 'UNCOLLECTED', 'PENALTY_APPLIED', 'CANCELLED', name='certificatestatus'),
               nullable=True)
    op.drop_column('certificates', 'revoked_at')
    op.drop_column('certificates', 'printed_at')
    op.drop_column('certificates', 'generated_at')
    op.drop_column('certificates', 'replacement_certificate_id')
    op.drop_column('certificates', 'revocation_reason')
    op.drop_column('certificates', 'blockchain_hash')
    op.drop_column('certificates', 'qr_code_path')
    op.drop_column('certificates', 'qr_code_data')
    op.drop_column('certificates', 'file_path')
    op.drop_column('certificates', 'revoked_by_id')
    op.drop_column('certificates', 'printed_by_id')
    op.drop_column('certificates', 'generated_by_id')
    op.add_column('audit_logs', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('user_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_identifier', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('certificate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('additional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_payment_id_fkey'), 'audit_logs', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_certificate_id_fkey'), 'audit_logs', 'certificates', ['certificate_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_application_id_fkey'), 'audit_logs', 'applications', ['application_id'], ['id'])
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'resource_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'LOGIN_FAILED', 'PASSWORD_CHANGED', 'PASSWORD_RESET', 'STATUS_CHANGED', 'DOCUMENT_UPLOADED', 'DOCUMENT_VERIFIED', 'DOCUMENT_REJECTED', 'PAYMENT_INITIATED', 'PAYMENT_CONFIRMED', 'CERTIFICATE_GENERATED', 'CERTIFICATE_PRINTED', 'APPLICATION_SUBMITTED', 'APPLICATION_APPROVED', 'APPLICATION_REJECTED', 'PENALTY_APPLIED', 'PENALTY_WAIVED', 'DELIVERY_ASSIGNED', 'EXPORT_DATA', 'BULK_ACTION', name='auditaction'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('audit_logs', 'extra_data')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'http_method')
    op.add_column('applications', sa.Column('child_birth_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('application_type', postgresql.ENUM('NEW_BIRTH', 'REPLACEMENT', 'CORRECTION', name='applicationtype'), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('father_full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('child_birth_city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('child_middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('assigned_staff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('mother_full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('additional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('expected_completion_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('child_birth_region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('applications_assigned_staff_id_fkey'), 'applications', 'users', ['assigned_staff_id'], ['id'])
    op.alter_column('applications', 'informant_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('applications', 'informant_relationship',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'informant_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('applications', 'mother_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('applications', 'child_place_of_birth',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('applications', 'child_gender',
               existing_type=sa.Enum('MALE', 'FEMALE', name='gender'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('applications', 'child_date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('applications', 'service_plan',
               existing_type=postgresql.ENUM('NORMAL', 'EXPRESS', name='serviceplan'),
               nullable=True)
    op.alter_column('applications', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PAYMENT_PENDING', 'PAYMENT_COMPLETED', 'PROCESSING', 'READY', 'COLLECTED', 'DELIVERED', 'CANCELLED', name='applicationstatus'),
               nullable=True)
    op.drop_column('applications', 'extra_data')
    op.drop_column('applications', 'delivered_at')
    op.drop_column('applications', 'collected_at')
    op.drop_column('applications', 'printed_at')
    op.drop_column('applications', 'confirmed_at')
    op.drop_column('applications', 'collection_deadline')
    op.drop_column('applications', 'ready_at')
    op.drop_column('applications', 'expected_ready_date')
    op.drop_column('applications', 'internal_notes')
    op.drop_column('applications', 'additional_info_request')
    op.drop_column('applications', 'total_fee')
    op.drop_column('applications', 'processing_fee')
    op.drop_column('applications', 'delivery_notes')
    op.drop_column('applications', 'delivery_fee')
    op.drop_column('applications', 'delivery_digital_address')
    op.drop_column('applications', 'delivery_district')
    op.drop_column('applications', 'delivery_region')
    op.drop_column('applications', 'delivery_address')
    op.drop_column('applications', 'attending_physician')
    op.drop_column('applications', 'hospital_address')
    op.drop_column('applications', 'hospital_name')
    op.drop_column('applications', 'mother_address')
    op.drop_column('applications', 'mother_date_of_birth')
    op.drop_column('applications', 'mother_other_names')
    op.drop_column('applications', 'mother_last_name')
    op.drop_column('applications', 'mother_first_name')
    op.drop_column('applications', 'father_address')
    op.drop_column('applications', 'father_date_of_birth')
    op.drop_column('applications', 'father_other_names')
    op.drop_column('applications', 'father_last_name')
    op.drop_column('applications', 'father_first_name')
    op.drop_column('applications', 'child_birth_order')
    op.drop_column('applications', 'child_nationality')
    op.drop_column('applications', 'child_district_of_birth')
    op.drop_column('applications', 'child_region_of_birth')
    op.drop_column('applications', 'child_other_names')
    op.drop_column('applications', 'delivery_method')
    op.drop_column('applications', 'reviewed_by_id')
    op.drop_column('applications', 'applicant_id')
    op.create_table('application_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('verification_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_documents_application_id_fkey')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('application_documents_verified_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('application_documents_pkey'))
    )
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('processing_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_plans_pkey')),
    sa.UniqueConstraint('name', name=op.f('payment_plans_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_payment_plans_id'), 'payment_plans', ['id'], unique=False)
    op.create_table('delivery_addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address_line1', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address_line2', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('landmark', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('delivery_addresses_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('delivery_addresses_pkey'))
    )
    op.create_index(op.f('ix_delivery_addresses_id'), 'delivery_addresses', ['id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('EMAIL', 'SMS', 'IN_APP', 'PUSH', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_templates_pkey')),
    sa.UniqueConstraint('name', name=op.f('notification_templates_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    # ### end Alembic commands ###
