"""add_accessibility_preferences_to_users

Revision ID: d2605220294d
Revises: b82ca6dd623d
Create Date: 2026-03-01 19:06:37.000782

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd2605220294d'
down_revision: Union[str, None] = 'b82ca6dd623d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accessibility_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accessibility_preferences')
    # ### end Alembic commands ###
