import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

export const LANGUAGES = [
  {
    code: 'en',
    label: 'English',
    native: 'English',
    bcp47: 'en-GH',
    regions: 'National (all regions)',
    speech: ['en-GH', 'en-GB', 'en'],
  },
  {
    code: 'tw',
    label: 'Twi',
    native: 'Twi (Akan)',
    bcp47: 'ak-GH',
    regions: 'Ashanti, Ahafo, Bono, Bono East, Eastern',
    speech: ['ak-GH', 'ak', 'en-GH', 'en'],
  },
  {
    code: 'fat',
    label: 'Fante',
    native: 'Mfantse',
    bcp47: 'fat-GH',
    regions: 'Central, parts of Western and Western North',
    speech: ['fat-GH', 'fat', 'ak-GH', 'ak', 'en-GH', 'en'],
  },
  {
    code: 'ee',
    label: 'Ewe',
    native: 'Eʋegbe',
    bcp47: 'ee-GH',
    regions: 'Volta and Oti',
    speech: ['ee-GH', 'ee', 'en-GH', 'en'],
  },
  {
    code: 'gaa',
    label: 'Ga',
    native: 'Gã',
    bcp47: 'gaa-GH',
    regions: 'Greater Accra',
    speech: ['gaa-GH', 'gaa', 'en-GH', 'en'],
  },
  {
    code: 'ha',
    label: 'Hausa',
    native: 'Hausa',
    bcp47: 'ha-GH',
    regions: 'Northern trade communities (nationwide)',
    speech: ['ha-GH', 'ha', 'en-GH', 'en'],
  },
  {
    code: 'dag',
    label: 'Dagbani',
    native: 'Dagbanli',
    bcp47: 'dag-GH',
    regions: 'Northern, North East, Savannah',
    speech: ['dag-GH', 'dag', 'en-GH', 'en'],
  },
  {
    code: 'dga',
    label: 'Dagaare',
    native: 'Dagaare',
    bcp47: 'dga-GH',
    regions: 'Upper West',
    speech: ['dga-GH', 'dga', 'en-GH', 'en'],
  },
  {
    code: 'gjn',
    label: 'Gonja',
    native: 'Ngmanja',
    bcp47: 'gjn-GH',
    regions: 'Savannah',
    speech: ['gjn-GH', 'gjn', 'en-GH', 'en'],
  },
];

const T = {
  en: {
    // Common
    yes: 'Yes',
    no: 'No',
    on: 'On',
    off: 'Off',
    or: 'or',
    optional: 'Optional',
    required: 'Required',
    default: 'Default',
    none: 'None',

    // Shell/nav
    home: 'Home',
    about: 'About',
    about_bdr: 'About BDR',
    bdr_purpose: 'BDR Purpose',
    registrar: 'The Registrar',
    rti: 'Right to Information',
    services: 'Services',
    our_services: 'Our Services',
    birth_reg_nav: 'Birth Registrations',
    death_reg_nav: 'Death Registrations',
    extracts: 'Extracts / True Copy',
    adoptions: 'Adoptions',
    verification: 'Verification',
    statistics_req: 'Statistics Data Request',
    statistics_request: 'Statistics Request',
    offices: 'Our Offices',
    regional_offices: 'Regional Offices',
    regions: 'Regions',
    faq: 'FAQs',
    contact: 'Contact',
    contact_us: 'Contact Us',
    media: 'Media',
    resources: 'Resources',
    quick_links: 'Quick Links',
    news_ann: 'News & Announcements',
    charter: 'Client Service Charter',
    downloads: 'Downloads',
    photo_gallery: 'Photo Gallery',
    sign_in: 'Sign In',
    sign_out: 'Sign Out',
    sign_up: 'Sign Up',
    create_account: 'Create Account',
    create_free_account: 'Create Free Account',
    dashboard: 'Dashboard',
    profile: 'My Profile',
    register_birth: 'Register a Birth',
    register_death: 'Register a Death',
    track: 'Track',
    track_application: 'Track Application',
    submit: 'Submit',
    cancel: 'Cancel',
    save: 'Save Changes',
    continue: 'Continue',
    back: 'Back',
    loading: 'Loading…',
    search: 'Search',
    close: 'Close',
    view_all: 'View All',
    read_more: 'Read More',
    learn_more: 'Learn More',
    get_started: 'Get Started',
    requirements: 'Requirements',
    process: 'Process',
    latest: 'Latest',
    coverage: 'Coverage',
    what_we_offer: 'What We Offer',

    // Language / theme / accessibility top bar
    language: 'Language',
    change_language: 'Change language',
    select_language: 'Select language',
    spoken_in_regions: 'Mainly spoken in: {regions}',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    active: 'Active',
    accessibility: 'Accessibility',
    accessibility_on: 'Accessibility (on)',
    accessibility_settings: 'Accessibility settings',
    accessibility_and_preferences: 'Accessibility and preferences',
    close_accessibility_panel: 'Close accessibility panel',
    visual: 'Visual',
    text_size: 'Text Size',
    decrease_text: 'Decrease text',
    increase_text: 'Increase text',
    reset_default: 'Reset to Default',
    high_contrast: 'High Contrast',
    negative_contrast: 'Negative Contrast',
    grayscale: 'Grayscale',

    // Accessibility widget sections
    open_accessibility_settings: 'Open accessibility settings',
    vision: 'Vision',
    reading: 'Reading',
    navigation: 'Navigation',
    screen_reader: 'Screen Reader',
    color_contrast: 'Color Contrast',
    color_blind: 'Color Blind',
    high: 'High',
    yellow: 'Yellow',
    sepia: 'Sepia',
    deuteranopia: 'Deuteranopia',
    protanopia: 'Protanopia',
    tritanopia: 'Tritanopia',
    saturation: 'Saturation',
    page_dimmer: 'Page Dimmer',
    page_zoom: 'Page Zoom',
    hide_images: 'Hide Images',
    bold_text: 'Bold Text',
    highlight_links: 'Highlight Links',
    line_spacing: 'Line Spacing',
    letter_spacing: 'Letter Spacing',
    word_spacing: 'Word Spacing',
    text_alignment: 'Text Alignment',
    auto: 'Auto',
    left: 'Left',
    center: 'Center',
    dyslexia_font: 'Dyslexia-friendly Font',
    underline_links: 'Underline Links',
    reading_guide_line: 'Reading Guide Line',
    stop_animations: 'Stop Animations',
    large_cursor: 'Large Cursor',
    highlight_focus: 'Highlight Focus',
    keyboard_navigation: 'Keyboard Navigation',
    skip_main_content: 'Skip to main content',
    read_page: 'Read Page Aloud',
    read_selection: 'Read Selection',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
    voice: 'Voice',
    speed: 'Speed',
    select_voice: 'Select voice',
    default_voice: 'Default Voice',
    not_supported: 'Not Supported',
    no_voice_lang: 'No voice available for this language — using default voice',

    // Home
    welcome: 'Welcome to the Ghana Births & Deaths Registry',
    tagline: 'Registering every life. Preserving every record.',
    birth_registration: 'Birth Registration',
    death_registration: 'Death Registration',
    certificate: 'Certificate',
    application_status: 'Application Status',
    verified: 'Verified',
    pending: 'Pending',
    rejected: 'Rejected',
    track_your_application: 'Track Your Application',
    enter_reference: 'Enter reference number (e.g. BDR-2024-000123)',
    application_reference_number: 'Application reference number',
    home_services_sub: "Ghana's official vital registration services — accessible online for all Ghanaians.",
    home_service_birth_desc: 'Register a new birth within 12 months for free. Online submission available for parents and authorized agents.',
    home_service_death_desc: 'Officially record a death and obtain burial permits and death certificates through our secure online platform.',
    home_service_track_desc: 'Use your unique reference number to check the real-time status of any submitted birth or death registration.',
    births_registered: 'Births Registered',
    deaths_recorded: 'Deaths Recorded',
    district_offices: 'District Offices',
    years_of_service: 'Years of Service',
    how_it_works: 'How It Works',
    home_process_sub: 'Four simple steps from application to certificate collection.',
    step_create_account_title: 'Create Account',
    step_create_account_desc: 'Sign up as a citizen or agent. Verification is instant and free.',
    step_submit_application_title: 'Submit Application',
    step_submit_application_desc: 'Complete the digital form with the required details and documents.',
    step_under_review_title: 'Under Review',
    step_under_review_desc: 'Our officers review and verify your submission within 5 to 10 business days.',
    step_collect_certificate_title: 'Collect Certificate',
    step_collect_certificate_desc: 'Collect your certificate from any district office with your reference number.',
    why_bdr: 'Why BDR',
    trusted_authority_title: "Ghana's Trusted Vital Registration Authority",
    trusted_authority_desc: 'Established in 1888, the Ghana Births and Deaths Registry has served Ghanaians for over 136 years. Our mandate is enshrined in the Constitution, ensuring every citizen has a legally recognized identity from birth.',
    why_bullet_free_birth: 'Free birth registration within 12 months',
    why_bullet_260_offices: '260+ district offices across all 16 regions',
    why_bullet_realtime_tracking: 'Real-time application tracking',
    why_bullet_international_cert: 'Internationally recognized certificates',
    why_bullet_secure_platform: 'Secure, government-certified digital platform',
    learn_more_about_bdr: 'Learn More About BDR',
    government_certified: 'Government Certified',
    application_success_rate: 'Application Success Rate',
    business_days_processing: 'Business Days Processing',
    annual_registrations: 'Annual Registrations',
    all_16_regions: 'All 16 Regions of Ghana',
    regions_sub: 'BDR offices are located in every region and district across Ghana.',
    region_suffix: 'Region',
    view_all_offices: 'View All Offices',
    welcome_back: 'Welcome back!',
    welcome_back_name: 'Welcome back, {name}!',
    dashboard_cta_desc: 'Access your dashboard to track applications, manage registrations, and view your certificates.',
    ready_to_register: 'Ready to Register?',
    register_cta_desc: 'Create a free account and submit your birth or death registration online in minutes.',
    go_to_dashboard: 'Go to Dashboard',

    // Carousel
    carousel_eyebrow_official: 'Official Portal',
    carousel_title_main: 'Ghana Births & Deaths Registry',
    carousel_sub_main: 'Your gateway to official vital registration services — fast, secure and fully digital across all 16 regions.',
    carousel_eyebrow_birth: 'Birth Registration',
    carousel_title_birth: 'Register Every Birth, Secure Every Future',
    carousel_sub_birth: 'Register a birth within 12 months and receive a certified birth certificate quickly and conveniently.',
    carousel_eyebrow_death: 'Death Registration',
    carousel_title_death: 'Dignified Death Registration Services',
    carousel_sub_death: 'Record and certify a death with care. Obtain official death certificates from any district office across Ghana.',
    carousel_eyebrow_track: 'Track & Collect',
    carousel_title_track: 'Real-Time Application Tracking',
    carousel_sub_track: 'Monitor your application status and get notified the moment your certificate is ready for collection.',
    previous_slide: 'Previous slide',
    next_slide: 'Next slide',
    slide_n: 'Slide {n}',

    // Footer
    ministry_name: 'Ministry of Local Government, Decentralisation and Rural Development',
    republic_of_ghana: 'Republic of Ghana',
    footer_desc: "The official digital portal of Ghana's Births and Deaths Registry. Secure, accurate, and accessible vital registration services for all Ghanaians.",
    office_hours: 'Monday to Friday, 8:00 AM to 5:00 PM',
    all_rights_reserved: 'All rights reserved.',
    privacy_policy: 'Privacy Policy',
    terms_of_service: 'Terms of Service',
    accessibility_statement: 'Accessibility Statement',
    report_issue: 'Report an Issue',
    go_to_top: 'Go to top of page',
    back_to_top: 'Back to top',

    // App shell
    page_not_found: 'Page Not Found',
    page_not_found_desc: 'The page you are looking for does not exist or has been moved.',
    return_home: 'Return to Home',

    // Sign in
    one_login: 'BDR One Login',
    all_government_services: 'All Government Services',
    sign_in_with_password: 'Sign in with Password',
    sign_in_with_digital_id: 'Sign in with Digital ID',
    email_address: 'Email address',
    enter_registered_email: 'Enter your registered email',
    password: 'Password',
    toggle_password_visibility: 'Toggle password visibility',
    hide_password: 'Hide Password',
    show_password: 'Show Password',
    remember_30_days: 'Remember for 30 days',
    forgot_password: 'Forgot Password',
    signing_in: 'Signing in...',
    digital_id_title: 'Sign in with Digital ID',
    digital_id_desc: 'Enter your registered ID number, then complete biometric verification. No password required.',
    id_type: 'ID Type',
    ghana_card: 'Ghana Card',
    passport_number: 'Passport Number',
    optional_metamap_scan: 'optional — MetaMap will scan it',
    ghana_card_number: 'Ghana Card Number',
    enter_passport_number: 'Enter passport number',
    scan_id_sign_in: 'Scan ID and Sign In',
    metamap_auto_verify: 'MetaMap will scan your document and verify your face automatically.',
    sign_in_without_biometric: 'Sign In without Biometric',
    sign_in_with_digital_id_btn: 'Sign In with Digital ID',
    enter_id_to_sign_in: 'Enter your ID number above to sign in',
    verifying_identity: 'Verifying identity…',
    no_account_prompt: "Don't have an account?",
    easy_access_services: 'You can now easily access government services.',
    err_use_registered_email: 'Use your registered email for password sign in, or switch to the Digital ID tab.',
    welcome_back_user: 'Welcome back, {name}!',
    err_invalid_credentials: 'Invalid credentials',
    err_enter_id_number: 'Please enter your ID number.',
    welcome_identity_verified: 'Welcome, {name}! Identity verified.',
    err_no_account_id: 'No account found with this ID. Please register first or check your ID number.',
    err_account_deactivated: 'Your account has been deactivated. Please contact support.',
    err_identity_verification_failed: 'Identity verification failed. Please try again.',

    // Sign up
    ghana_bdr: 'Ghana BDR',
    births_deaths_registry: 'Births & Deaths Registry',
    select_account_type: 'Select the account type that applies to you.',
    already_have_account: 'Already have an account?',
    citizen: 'Citizen',
    resident: 'Resident',
    refugee: 'Refugee',
    diplomat: 'Diplomat',
    foreigner: 'Foreigner',
    account_type_citizen_desc: 'For Ghana Citizens',
    account_type_resident_desc: 'For Foreign Residents',
    account_type_refugee_desc: 'For Refugees',
    account_type_diplomat_desc: 'For Diplomats within Ghana',
    account_type_foreigner_desc: 'For Visitors to Ghana',
    step_personal_info: 'Personal Info',
    step_contact_location: 'Contact & Location',
    step_security: 'Security',
    step_identity_verification: 'Identity Verification',
    step_of: 'Step {current} of {total} — {name}',
    change_type: 'Change type',
    first_name: 'First Name',
    last_name: 'Last Name',
    other_names: 'Other Names',
    date_of_birth: 'Date of Birth',
    nationality: 'Nationality',
    permit_type: 'Permit Type',
    permit_number: 'Permit Number',
    visa_type: 'Visa Type',
    phone_number: 'Phone Number',
    region: 'Region',
    district: 'District',
    address: 'Address',
    create_password: 'Create Password',
    confirm_password: 'Confirm Password',
    repeat_password: 'Repeat your password',
    terms_prompt: 'I agree to the Terms of Service and Privacy Policy',
    identity_notice_after_register: 'After registration, you will upload your Ghana Card to verify your identity and activate full access.',
    required_field: 'Required',
    valid_email_required: 'Valid email required',
    phone_format_gh: 'Use +233XXXXXXXXX or 0XXXXXXXXX',
    ghana_card_required: 'Ghana Card number is required',
    ghana_card_invalid_format: 'Invalid format. Must be GHA-XXXXXXXXX-X (e.g. GHA-123456789-0)',
    password_requirements: 'Password must be at least 8 characters with uppercase, lowercase, and a number',
    passwords_no_match: 'Passwords do not match',
    select_type: 'Select type',
    select_region: 'Select Region',
    select_visa_type: 'Select visa type',
    creating_account: 'Creating account…',
    processing: 'Processing…',
    create_account_continue: 'Create Account & Continue',
    complete_verification_to_continue: 'Complete verification above to continue',
    identity_verification_complete: 'Identity Verification Complete',
    identity_verification_complete_desc: 'Your verification has been submitted for review. Click below to go to your dashboard while we process it.',
    submitting_verification_data: 'Submitting verification data…',
    verify_identity_instruction: 'Verify your identity using your Ghana Card and a live selfie. This is powered by MetaMap identity verification. Your data is encrypted and processed securely.',
    identity_service_unavailable: 'Identity verification service is not configured. Please contact support.',
    exited_verification_prompt: 'You exited the verification. Please complete it to activate your account.',
    account_created_complete_verification: 'Account created. Complete identity verification to activate full access.',
    identity_verification_submitted: 'Identity verification submitted. Your account is being reviewed.',
    please_complete_verification: 'Please complete the identity verification above before continuing.',
    account_created_sign_in: 'Account created! Please sign in.',
    registration_failed_try_again: 'Registration failed. Please try again.',
    ghana_card_registered_continue_digital: 'This Ghana Card is already registered. Continue with Digital ID sign in.',
    ghana_card_registered_verify_signin: 'This Ghana Card is already registered. Verify your identity to sign in.',

    // Ghana Card verification component
    identity_verification: 'Identity Verification',
    verify_ghanaian_identity: 'Verify your Ghanaian identity to proceed with registration.',
    step_ghana_card_details: 'Step 1: Ghana Card Details',
    step_liveness_photo: 'Step 2: Liveness Photo',
    verified_short: 'Verified',
    card_number_required: 'Ghana Card number is required.',
    card_number_invalid: 'Enter a valid Ghana Card number (GHA-XXXXXXXXX-X).',
    dob_required_verification: 'Date of birth is required for verification.',
    card_photo_required: 'Please upload a photo of your Ghana Card.',
    card_verify_failed: 'Ghana Card verification failed. Please check your card number and date of birth.',
    camera_access_denied: 'Camera access denied. Please upload a selfie photo instead.',
    selfie_required: 'Please take or upload a photo of yourself.',
    face_comparison_failed: 'Face comparison failed. The selfie does not match the document photo. Please try again.',
    the_file_may_not_be_ghana_card: 'The file you selected may not be a Ghana National ID Card. Please ensure you upload a clear photo of your Ghana Card (the green/gold card issued by the National Identification Authority), not a passport, driver\'s license, or other document.',
    ghana_card_step: 'Ghana Card',
    liveness_photo_step: 'Liveness Photo',
    ghana_card_photo: 'Ghana Card Photo',
    remove_card_image: 'Remove card image',
    upload_ghana_card_photo: 'Upload a clear photo of your Ghana Card',
    image_format_hint: 'JPG, PNG or WEBP — max 5 MB',
    verify_ghana_card_btn: 'Verify Ghana Card',
    verifying: 'Verifying...',
    skip_testing_only: 'Skip (for testing only)',
    ghana_card_verified_badge: 'Ghana Card verified',
    selfie_instruction: 'Take a clear photo of your face in good lighting. Ensure your face matches the photo on your Ghana Card.',
    capture_photo: 'Capture Photo',
    retake: 'Retake',
    use_camera: 'Use Camera',
    upload_photo: 'Upload Photo',
    comparing_faces: 'Comparing faces...',
    confirm_identity: 'Confirm Identity',
    identity_verified: 'Identity Verified',
    identity_verified_desc: 'Your Ghanaian identity has been successfully verified. You may now proceed with registration.',
    verified_user: 'Verified user',
    your_data_encrypted_note: 'Your Ghana Card information is verified against the NIA database. Data is encrypted and not stored beyond this session.',

    // Password checks
    pw_length_8: 'Length 8+',
    pw_uppercase: 'Uppercase',
    pw_lowercase: 'Lowercase',
    pw_number: 'Number',
  },

  tw: {
    home: 'Fie',
    about: 'Yɛn Ho',
    services: 'Adwuma',
    offices: 'Yɛn Afisɛm',
    regions: 'Mantam',
    faq: 'Nsɛmmisa',
    contact: 'Kasa Yɛn Ho',
    media: 'Amanneɛ',
    news_ann: 'Amanneɛ ne Nkaebɔ',
    downloads: 'Twe',
    photo_gallery: 'Mfonini',
    sign_in: 'Hyɛ Wo Din',
    sign_out: 'Pue',
    create_account: 'Bueɛ Akawnt',
    dashboard: 'Dashboard',
    profile: 'Me Ho Nsɛm',
    register_birth: 'Kyerɛw Awoɔ',
    register_death: 'Kyerɛw Owuo',
    track: 'Di Aplikɛhyɛn Akyi',
    submit: 'Fa Kɔ',
    cancel: 'Gyae',
    continue: 'Kɔ So',
    back: 'San Kɔ',
    loading: 'Rehwehwɛ…',
    search: 'Hwehwɛ',
    close: 'To Mu',
    language: 'Kasa',
    change_language: 'Sesa Kasa',
    select_language: 'Yi Kasa',
    spoken_in_regions: 'Wɔka kasa yi kɛse wɔ: {regions}',
    accessibility: 'Nnyinaso Mmoa',
    accessibility_settings: 'Nnyinaso mmoa nhyehyɛe',
    text_size: 'Nkyerɛwee Kɛse',
    reset_default: 'San Kɔ Default',
    high_contrast: 'Mfonini Mu Denden',
    negative_contrast: 'Aduannuru Akyiri',
    grayscale: 'Nwunu/Nwawa',
    theme: 'Ahosuo',
    light: 'Hann',
    dark: 'Sum',
    system: 'Sistɛm',
    active: 'Ɛreyɛ Adwuma',
    read_page: 'Kenkan Krataa',
    read_selection: 'Kenkan De Wuyi',
    stop: 'Gyae',
    pause: 'Gyina',
    resume: 'Toa So',
    voice: 'Ɛnne',
    speed: 'Ntɛmntɛm',
    no_voice_lang: 'Wonnya nne mma kasa yi — yɛde default nne bɛyɛ adwuma',
    not_supported: 'Nni Mmoa',
    default_voice: 'Default Nne',
    page_not_found: 'Wonnhu Kratafa No',
    page_not_found_desc: 'Kratafa a worehwehwɛ no nni hɔ anaa wɔatu afiri ha.',
    return_home: 'San Kɔ Fie',
    one_login: 'BDR Hyɛ Wo Din Baako',
    all_government_services: 'Aban adwuma nyinaa',
    sign_in_with_password: 'Hyɛ wo din de password',
    sign_in_with_digital_id: 'Hyɛ wo din de Digital ID',
    email_address: 'Email Address',
    enter_registered_email: 'Hyɛ wo email a wokyerɛw no',
    password: 'Password',
    remember_30_days: 'Kae me nnansa aduasa',
    forgot_password: 'Wowerɛ password?',
    signing_in: 'Rehyɛ wo din...',
    digital_id_title: 'Hyɛ wo din de Digital ID',
    digital_id_desc: 'Hyɛ wo ID nɔma no, afei yɛ biometric nsiho. Password ho nhia.',
    id_type: 'ID Su',
    ghana_card: 'Ghana Card',
    passport_number: 'Passport Nɔma',
    optional_metamap_scan: 'optional — MetaMap bɛscan ama wo',
    ghana_card_number: 'Ghana Card Nɔma',
    enter_passport_number: 'Hyɛ passport nɔma',
    scan_id_sign_in: 'Scan ID na Hyɛ Wo Din',
    metamap_auto_verify: 'MetaMap bɛscan krataa no na ɛde wo anim ahwɛ.',
    sign_in_without_biometric: 'Hyɛ Wo Din a Biometric Nni Mu',
    sign_in_with_digital_id_btn: 'Hyɛ Wo Din de Digital ID',
    enter_id_to_sign_in: 'Hyɛ wo ID nɔma no wɔ atifi ha',
    verifying_identity: 'Rehwɛ wo ho nsɛm mu…',
    no_account_prompt: 'Wonni akawnt anaa?',
    sign_up: 'Kyerɛw Wo Ho',
    easy_access_services: 'Afei wobetumi anya aban adwuma ntɛm.',
    track_your_application: 'Di W\'aplikɛhyɛn Akyi',
    enter_reference: 'Hyɛ reference nɔma no (sɛ: BDR-2024-000123)',
    application_reference_number: 'Aplikɛhyɛn reference nɔma',
    what_we_offer: 'De Yɛde Ma',
    home_services_sub: 'Ghana adwuma a ɛfa awoɔ ne owuo nkyerɛwmu ho — obiara betumi de intanɛt so adi dwuma.',
    births_registered: 'Awoɔ a Wɔakyerɛw',
    deaths_recorded: 'Owuo a Wɔakyerɛw',
    district_offices: 'Mansini Afisɛm',
    years_of_service: 'Mfe a Yɛde Asom',
    how_it_works: 'Sɛ Ɛyɛ Adwuma',
    home_process_sub: 'Anammɔn 4 pɛ na ɛde wo bɛkɔ certificate no so.',
    latest: 'Foforo',
    view_all: 'Hwɛ Nyinaa',
    read_more: 'Kenkan Pii',
    why_bdr: 'Adɛn nti na BDR',
    all_16_regions: 'Ghana Mantam 16 Nyinaa',
    regions_sub: 'BDR afisɛm wɔ mantam ne mansini nyinaa mu.',
    region_suffix: 'Mantam',
    view_all_offices: 'Hwɛ Afisɛm Nyinaa',
    welcome_back: 'Akwaaba bio!',
    welcome_back_name: 'Akwaaba bio, {name}!',
    ready_to_register: 'Woasiesie wo ho sɛ wobɛkyerɛw?',
    go_to_dashboard: 'Kɔ Dashboard',
    create_free_account: 'Yɛ Akawnt kwa',
    contact_us: 'Kasa Yɛn Ho',
    ministry_name: 'Ministry of Local Government, Decentralisation and Rural Development',
    republic_of_ghana: 'Republic of Ghana',
    resources: 'Mmoa',
    quick_links: 'Ntetee Kwan',
    office_hours: 'Dwoada–Fiada, 8:00 AM – 5:00 PM',
    all_rights_reserved: 'Hokwan nyinaa yɛn dea.',
    privacy_policy: 'Kokoam Nhyehyɛe',
    terms_of_service: 'Asetena Mmara',
    accessibility_statement: 'Nnyinaso Mmoa Asɛm',
    report_issue: 'Bɔ Asɛm Ho Amaneɛ',
    go_to_top: 'Kɔ kratafa no atifi',
    back_to_top: 'San kɔ atifi',
    identity_verification: 'Nipadua Ho Nhyɛmu',
    verify_ghanaian_identity: 'Hwɛ wo Ghana nipadua ho nkyerɛmu ansa na woatoa so.',
    step_ghana_card_details: 'Anammɔn 1: Ghana Card Nsɛm',
    step_liveness_photo: 'Anammɔn 2: Wo Mfonini',
    ghana_card_photo: 'Ghana Card Mfonini',
    upload_ghana_card_photo: 'Fa wo Ghana Card mfonini a emu da hɔ gu so',
    verify_ghana_card_btn: 'Hwɛ Ghana Card Mu',
    comparing_faces: 'Rede anim ahwɛ…',
    confirm_identity: 'Si Nipadua No So Dua',
    identity_verified: 'Wɔasi Nipadua no so Dua',
    identity_verified_desc: 'Yɛasi wo Ghana nipadua so dua yiye. Afei wubetumi atoa so akyerɛw.',
    verified_user: 'Wɔasi so dua',
  },

  ha: {
    home: 'Gida',
    about: 'Game da Mu',
    services: 'Ayyuka',
    offices: 'Ofisoshinmu',
    regions: 'Yankuna',
    faq: 'Tambayoyi',
    contact: 'Tuntuɓe Mu',
    media: 'Labarai',
    news_ann: 'Labarai da Sanarwa',
    downloads: 'Sauke',
    photo_gallery: 'Hotuna',
    sign_in: 'Shiga',
    sign_out: 'Fita',
    create_account: 'Ƙirƙiri Asusu',
    dashboard: 'Dashboard',
    profile: 'Bayani na',
    register_birth: 'Yi Rajistar Haihuwa',
    register_death: 'Yi Rajistar Mutuwa',
    track: 'Bibiya',
    track_application: 'Bibiya Bukata',
    submit: 'Aika',
    cancel: 'Soke',
    continue: 'Ci gaba',
    back: 'Koma baya',
    loading: 'Ana lodawa…',
    search: 'Nema',
    close: 'Rufe',
    language: 'Harshe',
    change_language: 'Canja Harshe',
    select_language: 'Zaɓi Harshe',
    spoken_in_regions: 'An fi magana da wannan a: {regions}',
    accessibility: 'Sauƙaƙen Amfani',
    accessibility_settings: 'Saitunan Sauƙaƙe',
    text_size: 'Girman Rubutu',
    reset_default: 'Mayar da asali',
    high_contrast: 'Babban bambanci',
    negative_contrast: 'Bambancin baya',
    grayscale: 'Baƙi da fari',
    theme: 'Jigo',
    light: 'Haske',
    dark: 'Duhu',
    system: 'Tsari',
    active: 'Aiki',
    read_page: 'Karanta Shafi',
    read_selection: 'Karanta Zaɓaɓɓe',
    stop: 'Tsaya',
    pause: 'Dakata',
    resume: 'Ci gaba',
    voice: 'Murya',
    speed: 'Sauri',
    no_voice_lang: 'Babu muryar wannan harshe — ana amfani da ta asali',
    not_supported: 'Ba ya goyan baya',
    default_voice: 'Muryar Asali',
    page_not_found: 'Ba a sami shafin ba',
    page_not_found_desc: 'Shafin da kake nema babu shi ko an matsar da shi.',
    return_home: 'Koma Gida',
    one_login: 'Shiga Daya ta BDR',
    all_government_services: 'Dukkan ayyukan gwamnati',
    sign_in_with_password: 'Shiga da Kalmar sirri',
    sign_in_with_digital_id: 'Shiga da Digital ID',
    email_address: 'Adireshin Imel',
    enter_registered_email: 'Shigar da imel ɗinka da aka yi rajista da shi',
    password: 'Kalmar sirri',
    remember_30_days: 'Ka tuna da ni na kwana 30',
    forgot_password: 'Ka manta kalmar sirri?',
    signing_in: 'Ana shiga...',
    digital_id_title: 'Shiga da Digital ID',
    digital_id_desc: 'Shigar da lambar ID ɗinka sannan ka kammala tabbatarwa ta biometric.',
    id_type: 'Nau\'in ID',
    ghana_card: 'Katin Ghana',
    passport_number: 'Lambar Fasfo',
    optional_metamap_scan: 'zaɓi ne — MetaMap zai duba ta',
    ghana_card_number: 'Lambar Katin Ghana',
    enter_passport_number: 'Shigar da lambar fasfo',
    scan_id_sign_in: 'Duba ID ka Shiga',
    metamap_auto_verify: 'MetaMap zai duba takardu da fuska ta atomatik.',
    sign_in_without_biometric: 'Shiga ba tare da biometric ba',
    sign_in_with_digital_id_btn: 'Shiga da Digital ID',
    enter_id_to_sign_in: 'Shigar da lambar ID a sama don shiga',
    verifying_identity: 'Ana tabbatar da shaida…',
    no_account_prompt: 'Ba ka da asusu?',
    sign_up: 'Yi rajista',
    easy_access_services: 'Yanzu zaka iya samun ayyukan gwamnati cikin sauƙi.',
    track_your_application: 'Bibiya Bukatarka',
    enter_reference: 'Shigar da lambar magana (misali: BDR-2024-000123)',
    application_reference_number: 'Lambar magana ta bukata',
    what_we_offer: 'Abin da muke bayarwa',
    home_services_sub: 'Ayyukan rajistar muhimman bayanai na Ghana da ake samu ta yanar gizo.',
    births_registered: 'Haihuwa da aka yi rajista',
    deaths_recorded: 'Mutuwa da aka rubuta',
    district_offices: 'Ofisoshin Gunduma',
    years_of_service: 'Shekarun Aiki',
    how_it_works: 'Yadda yake aiki',
    home_process_sub: 'Matakai huɗu masu sauƙi daga aikace-aikace zuwa karɓar takarda.',
    latest: 'Sabbi',
    view_all: 'Duba Duka',
    read_more: 'Kara karantawa',
    why_bdr: 'Me ya sa BDR',
    all_16_regions: 'Dukkan Yankuna 16 na Ghana',
    regions_sub: 'Ofisoshin BDR suna cikin kowane yanki da gunduma a Ghana.',
    region_suffix: 'Yanki',
    view_all_offices: 'Duba Dukkan Ofisoshi',
    welcome_back: 'Barka da dawowa!',
    welcome_back_name: 'Barka da dawowa, {name}!',
    ready_to_register: 'Kana shirye don rajista?',
    go_to_dashboard: 'Je zuwa Dashboard',
    create_free_account: 'Ƙirƙiri asusu kyauta',
    contact_us: 'Tuntuɓe Mu',
    ministry_name: 'Ma\'aikatar Kananan Hukumomi, Rarraba Iko da Raya Karkara',
    republic_of_ghana: 'Jamhuriyar Ghana',
    resources: 'Albarkatu',
    quick_links: 'Hanyoyi Masu Sauri',
    office_hours: 'Litinin–Juma\'a, 8:00 AM – 5:00 PM',
    all_rights_reserved: 'An kiyaye dukkan haƙƙoƙi.',
    privacy_policy: 'Tsarin Sirri',
    terms_of_service: 'Sharuɗɗan Aiki',
    accessibility_statement: 'Sanarwar Sauƙaƙe',
    report_issue: 'Kai Rahoton Matsala',
    go_to_top: 'Je saman shafi',
    back_to_top: 'Koma sama',
    identity_verification: 'Tabbatar da Shaida',
    verify_ghanaian_identity: 'Tabbatar da shaidarka ta Ghana domin ci gaba da rajista.',
    step_ghana_card_details: 'Mataki na 1: Bayanan Katin Ghana',
    step_liveness_photo: 'Mataki na 2: Hoton Fuska',
    ghana_card_photo: 'Hoton Katin Ghana',
    upload_ghana_card_photo: 'Loda hoto mai haske na Katin Ghana ɗinka',
    verify_ghana_card_btn: 'Tabbatar da Katin Ghana',
    comparing_faces: 'Ana kwatanta fuska...',
    confirm_identity: 'Tabbatar da Shaida',
    identity_verified: 'An Tabbatar da Shaida',
    identity_verified_desc: 'An tabbatar da shaidarka ta Ghana cikin nasara. Yanzu zaka iya ci gaba da rajista.',
    verified_user: 'An tabbatar da mai amfani',
  },

  ee: {
    home: 'Ƒe',
    about: 'Mía Ŋutinya',
    services: 'Dɔwɔwɔ',
    sign_in: 'Ŋlɔ Wò ŋkɔ',
    sign_out: 'Yi Egbe',
    create_account: 'Wɔ account',
    language: 'Gbe',
    change_language: 'Trɔ gbe',
  },

  gaa: {
    home: 'Hee',
    about: 'Mii Shishi',
    services: 'Gbɛ Yɛlɛ',
    sign_in: 'Tsɔɔ Wɔ Hɛ',
    sign_out: 'Yi',
    create_account: 'Bu account',
    language: 'Kɛlɛ',
    change_language: 'Shɛ Kɛlɛ',
  },

  dag: {
    home: 'Duu',
    about: 'Ti Zuɣu',
    services: 'Tiŋ Dabari',
    sign_in: 'Kpɛm',
    sign_out: 'Yi',
    create_account: 'Tigili account',
    language: 'Kasa',
    change_language: 'Suhim Kasa',
  },

  fat: {
    home: 'Efi',
    about: 'Yɛn Ho',
    services: 'Dwuma',
    sign_in: 'Hyɛ Wo Din',
    sign_out: 'Pue',
    create_account: 'Yɛ Account',
    language: 'Kasa',
    change_language: 'Sesa Kasa',
  },

  dga: {
    home: 'Yire',
    about: 'Ti Yela',
    services: 'Tuo',
    sign_in: 'Gane',
    sign_out: 'Yiri',
    create_account: 'Ma account',
    language: 'Yele',
    change_language: 'Bie yele',
  },

  gjn: {
    home: 'Ewura',
    about: 'Nya Biala',
    services: 'Nɔŋa',
    sign_in: 'Nya',
    sign_out: 'Fuo',
    create_account: 'Lebi account',
    language: 'Ngmanja',
    change_language: 'Sɛ ngmanja',
  },
};

function interpolate(template, vars = {}) {
  if (typeof template !== 'string') return template;
  return template.replace(/\{(\w+)\}/g, (_, k) => (vars[k] == null ? '' : String(vars[k])));
}

function getLanguageMeta(code) {
  return LANGUAGES.find((l) => l.code === code) || LANGUAGES[0];
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('bdr_lang');
    return saved && T[saved] ? saved : 'en';
  });

  const languageMeta = useMemo(() => getLanguageMeta(lang), [lang]);
  const bcp47 = languageMeta.bcp47 || 'en-GH';
  const speechLangCandidates = useMemo(() => {
    const candidates = languageMeta.speech || [bcp47, bcp47.split('-')[0], 'en-GH', 'en'];
    return Array.from(new Set(candidates.filter(Boolean)));
  }, [bcp47, languageMeta.speech]);

  useEffect(() => {
    document.documentElement.setAttribute('lang', bcp47);
  }, [bcp47]);

  const changeLang = useCallback((code) => {
    if (!T[code]) return;
    const nextMeta = getLanguageMeta(code);
    setLang(code);
    localStorage.setItem('bdr_lang', code);
    document.documentElement.setAttribute('lang', nextMeta.bcp47 || code);
  }, []);

  const t = useCallback((key) => T[lang]?.[key] ?? T.en?.[key] ?? key, [lang]);
  const tf = useCallback((key, vars) => interpolate(t(key), vars), [t]);

  return (
    <LanguageContext.Provider
      value={{
        lang,
        changeLang,
        t,
        tf,
        bcp47,
        speechLangCandidates,
        languageMeta,
        languages: LANGUAGES,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
